/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as AuthProjectsRouteImport } from './routes/_auth/projects'
import { Route as AuthInventoryRouteImport } from './routes/_auth/inventory'
import { Route as AuthGuideRouteImport } from './routes/_auth/guide'
import { Route as AuthFinancialsRouteImport } from './routes/_auth/financials'
import { Route as AuthChatSessionIdRouteImport } from './routes/_auth/chat.$sessionId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProjectsRoute = AuthProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInventoryRoute = AuthInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGuideRoute = AuthGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFinancialsRoute = AuthFinancialsRouteImport.update({
  id: '/financials',
  path: '/financials',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChatSessionIdRoute = AuthChatSessionIdRouteImport.update({
  id: '/chat/$sessionId',
  path: '/chat/$sessionId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/financials': typeof AuthFinancialsRoute
  '/guide': typeof AuthGuideRoute
  '/inventory': typeof AuthInventoryRoute
  '/projects': typeof AuthProjectsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/chat/$sessionId': typeof AuthChatSessionIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/financials': typeof AuthFinancialsRoute
  '/guide': typeof AuthGuideRoute
  '/inventory': typeof AuthInventoryRoute
  '/projects': typeof AuthProjectsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthIndexRoute
  '/chat/$sessionId': typeof AuthChatSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/financials': typeof AuthFinancialsRoute
  '/_auth/guide': typeof AuthGuideRoute
  '/_auth/inventory': typeof AuthInventoryRoute
  '/_auth/projects': typeof AuthProjectsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/chat/$sessionId': typeof AuthChatSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/financials'
    | '/guide'
    | '/inventory'
    | '/projects'
    | '/auth/callback'
    | '/chat/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/financials'
    | '/guide'
    | '/inventory'
    | '/projects'
    | '/auth/callback'
    | '/'
    | '/chat/$sessionId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/_auth/financials'
    | '/_auth/guide'
    | '/_auth/inventory'
    | '/_auth/projects'
    | '/auth/callback'
    | '/_auth/'
    | '/_auth/chat/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/projects': {
      id: '/_auth/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthProjectsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inventory': {
      id: '/_auth/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthInventoryRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/guide': {
      id: '/_auth/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof AuthGuideRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/financials': {
      id: '/_auth/financials'
      path: '/financials'
      fullPath: '/financials'
      preLoaderRoute: typeof AuthFinancialsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/chat/$sessionId': {
      id: '/_auth/chat/$sessionId'
      path: '/chat/$sessionId'
      fullPath: '/chat/$sessionId'
      preLoaderRoute: typeof AuthChatSessionIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthFinancialsRoute: typeof AuthFinancialsRoute
  AuthGuideRoute: typeof AuthGuideRoute
  AuthInventoryRoute: typeof AuthInventoryRoute
  AuthProjectsRoute: typeof AuthProjectsRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthChatSessionIdRoute: typeof AuthChatSessionIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthFinancialsRoute: AuthFinancialsRoute,
  AuthGuideRoute: AuthGuideRoute,
  AuthInventoryRoute: AuthInventoryRoute,
  AuthProjectsRoute: AuthProjectsRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthChatSessionIdRoute: AuthChatSessionIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
